### ISSUE TITLE
SimTranslator.loadSimModel - simxml files and pathes

### ISSUE THREAD

**Issue by PRemmen** [EnEff-BIM/EnEffBIM-Framework#129]
If I try to run the above mentioned class/function from another script then runme.py or if i move the simxml files to another folder (and change the paths in the script) the function crashes. Can anyone reproduce this error?

**Comment by math-boy** [comment]
@PRemmen pls check the following two issues before you move the simxml file into the other location:
1) in the new release, we added the support for some new SimModel classes. Therefore, at the running script, we need to import these classes. You can copy these classe names from the runme.py
2) After we move the simxml file into a new location, we need to reset the value of the property 'xsi:schemaLocation' at the simxml file. HowTo:
2.1) use an xml editor, e.g., visual studio, to open the simxml file
2.2) find the property: xsi:schemaLocation' (normally at the top of the file)
2.3) reset the value 'simmodel_schema_15.10.30\simmodel.xsd' into the new directory that refers to the schema. For example, if we move the simxml file into the sub-folder 'use_case' within the 'Release'. Then we will reset this value as: '..\simmodel_schema_15.10.30\simmodel.xsd'

If you find the other problem of the code, pls write down the problem at github. I will check them after my holiday.

Best regards,

Jun

**Comment by math-boy** [comment]
?Hi Peter,

pls check my answer at the GitHub page.


Jun

________________________________

**Comment by PRemmen** [comment]
@math-boy perfect, thanks a lot, i forgot to import the new classes.
