### ISSUE TITLE
Bind Dicts in C++

### ISSUE THREAD

**Issue by PRemmen** [EnEff-BIM/EnEffBIM-Framework#83]
During the discussion with Jun, he proposed the following idea:

He can create binded dicts with the refID and the corresponding Object on C++ side. This would help to create the MappedHierarchy because we would have to iterate less.

It could something like this

```python

SimBuildingDict = {"refID1": SimBuildingObject1, "refID2": SimBuildingObject2}
```

this can then be done with every SimModel Object.

For me this sounds like a very good and efficient way to combine Object and refID parsing. 

Of course the binding of the c++ Framework to a general API has to be done first. So this issue is just to write down this idea for later, when the binding is done.

**Comment by TobiasMaile** [comment]
We do not want to use this anymore.
