### ISSUE TITLE
Tilt and Orientation into SimSpaceBoundary

### ISSUE THREAD

**Issue by PRemmen** [EnEff-BIM/EnEffBIM-Framework#94]
put these two attributes somewhere into the libSimModelAPI, and check if we can use Simergy functions

**Comment by TobiasMaile** [comment]
After the next SimModel update we will have those properties available.

**Comment by carlesRT** [comment]
Is it possible that the issue is already solved?
I have seen (From Juns API) that `SimSpaceBoundary_SecondLevel_SubTypeA` always includes the child `SimGeomVector_Vecor_Direction`, which value can be used to calculate the tillt and orientation of the boundary.

**Comment by PRemmen** [comment]
yes, solved and implemented (teaser fork)
